<?php
/**
 * @author    Marcin Frymark
 * @email     contact@alekseon.com
 * @company   Alekseon
 * @website   www.alekseon.com
 */
?>
<?php $options = $this->getColumn()->getOptions() ?>
<?php $disabled = '' ?>
<?php if ($this->getDisabled()): ?>
    <?php $disabled = 'disabled="disabled"' ?>    
<?php endif ?>
<span <?php if ($this->getHidden()) { echo 'style="display:none"'; } ?>>
    <select name="<?php echo $this->getName() ?>[value]" id="<?php echo $this->getName() ?>" <?php echo $disabled ?> onchange="rowChanged(<?php echo $this->getRowId() ?>)" >
        <?php if ($options): ?>
            <?php foreach($options as $optionsValue => $label): ?>
                <?php if ($this->getValue() == $optionsValue): ?>
                    <option value="<?php echo $optionsValue ?>" selected="selected"><?php echo $label ?></option>
                <?php else: ?>
                    <option value="<?php echo $optionsValue ?>"><?php echo $label ?></option>
                <?php endif ?>
            <?php endforeach ?>
        <?php else: ?>
            <option value="<?php echo $this->getValue() ?>" selected="selected"><?php echo $this->getValue() ?></option>
        <?php endif ?>
    </select>
</span>